### PR TITLE
Addressing some CRAN notes/errors + adding Poisson to Latin hypercube sampling

### PR DESCRIPTION
**Pull request by japilo**
See specific commit messages below for details.

### CODE REVIEW

**Comment by scbrown86** [comment]
@seanhaythorne I've had a quick look and didn't notice any issues

**Comment by scbrown86** [comment]
I don't know if these can be merged now due to the changes to the density dependent dispersal via target N/K that Sean made while you were doing this? The poisson LHS changes should be fine, but the others will conflict with changes to the Generator.R, PopulationModel.R, population_dispersal.R, and population_simulator.R - see https://github.com/GlobalEcologyLab/poems/commit/b0e18f52b2877593e6f750548f3bdc63d750607f

**Comment by japilo** [comment]
I think it should merge pretty easily? All I did to Generator.R, PopulationModel.R, population_dispersal.R, and population_simulator.R was change it so that functions are called from other packages with an `@importFrom` statement instead of a `pkg::` syntax, because the latter caused some ERRORs and NOTEs in Linux test environments.

**Comment by scbrown86** [comment]
This is all done now @japilo

**Pull request merged**
